server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/exclusiver/springcloud-config.git
          search-paths:
            - springcoud-config
      label: master
config:
  info: helloworld,version=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
